language: node_js
node_js:
    - "5"
before_script:
    - npm install gulp -g
    - npm install
script: 
    - gulp run-tests
env:
    - DATABASE_URL="postgres://ybblqxvs:GCYNSQW0othmnzhzmvPmm4kTgaODqW1j@stampy.db.elephantsql.com:5432/ybblqxvs"